spring.application.name=spring

management.endpoints.web.exposure.include=*
management.info.env.enabled=true

info.app.name=My Cool app
info.app.description=Seriously this is a really cool app 
info.app.version=1.0.0

spring.security.user.name=admin
spring.security.user.password=Password!

logging.file.name=logs/app.log 

logging.level.com.spring.demo.rest=DEBUG
logging.logback.rollingpolicy.file-name-pattern=logs/app.%d{yyyy-MM-dd}.%i.log.gz
logging.logback.rollingpolicy.max-file-size=10MB
logging.logback.rollingpolicy.max-history=7

spring.main.lazy-initialization=true